//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.ProductsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsServiceReference.IProducts", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IProducts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/AddCateogry", ReplyAction="http://tempuri.org/IProducts/AddCateogryResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void AddCateogry(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/AddCateogry", ReplyAction="http://tempuri.org/IProducts/AddCateogryResponse")]
        System.Threading.Tasks.Task AddCateogryAsync(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/AddProducts", ReplyAction="http://tempuri.org/IProducts/AddProductsResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        int AddProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducts/AddProducts", ReplyAction="http://tempuri.org/IProducts/AddProductsResponse")]
        System.Threading.Tasks.Task<int> AddProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsChannel : WindowsClient.ProductsServiceReference.IProducts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsClient : System.ServiceModel.ClientBase<WindowsClient.ProductsServiceReference.IProducts>, WindowsClient.ProductsServiceReference.IProducts {
        
        public ProductsClient() {
        }
        
        public ProductsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCateogry(string CategoryName) {
            base.Channel.AddCateogry(CategoryName);
        }
        
        public System.Threading.Tasks.Task AddCateogryAsync(string CategoryName) {
            return base.Channel.AddCateogryAsync(CategoryName);
        }
        
        public int AddProducts() {
            return base.Channel.AddProducts();
        }
        
        public System.Threading.Tasks.Task<int> AddProductsAsync() {
            return base.Channel.AddProductsAsync();
        }
    }
}
